"use client";

import { Topic } from "@/type/topic";
// import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import { useEffect, useState } from "react";

// export const metadata: Metadata = {
//   title: "Web tutorial",
//   description: "Generated by jisoo",
// };

// 페이지를 처음으로 렌더링 하는 부분이 layout.tsx 부분
// 모든페이지에 공통으로 제시사키고 싶은 부분이 있다면, {children} 밖 즉, layout.tsx애 적는 것이 맞갰지.
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [topics, setTopics] = useState<Topic[]>([]);

  useEffect(() => {
    fetch("http://localhost:9999/topics")
      .then((res) => {
        return res.json();
      })
      .then((result) => {
        return setTopics(result);
      });
  }, []);

  return (
    <html>
      <body>
        <h1>
          <Link href="/">Web</Link>
        </h1>
        <ol>
          {topics.map((item) => (
            <li key={item.id}>
              <Link href="/read/2">{item.title}</Link>
            </li>
          ))}
        </ol>
        {children} {/* 여기 있는 children은 page.tsx를 의미 */}
        <ul>
          <li>
            <Link href="/create">Create</Link>
          </li>
          <li>
            <Link href="/update/1">Update</Link>
          </li>
          <li>
            <input type="button" value="Delete" />
          </li>
        </ul>
      </body>
    </html>
  );
}
