import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Web tutorial",
  description: "Generated by jisoo",
};

// 페이지를 처음으로 렌더링 하는 부분이 layout.tsx 부분
// 모든페이지에 공통으로 제시사키고 싶은 부분이 있다면, {children} 밖 즉, layout.tsx애 적는 것이 맞갰지.
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html>
      <body>
        <h1><Link href="/">Web</Link></h1>
        <ol>
          <li><Link href="/read/1">html</Link></li>
          <li><Link href="/read/2">css</Link></li>
        </ol>
        {children} {/* 여기 있는 children은 page.tsx를 의미 */}
        <ul>
          <li><Link href="/create">Create</Link></li>
          <li><Link href="/update/1">Update</Link></li>
          <li><input type="button" value="Delete"/></li>
        </ul>
      </body>
    </html>
  );
}
