import { Topic } from "@/type/topic";
import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import TopicButtons from "@/component/Button/TopicButtons";

export const metadata: Metadata = {
  title: "Web tutorial",
  description: "Generated by jisoo",
};

// 페이지를 처음으로 렌더링 하는 부분이 layout.tsx 부분
// 모든페이지에 공통으로 제시사키고 싶은 부분이 있다면, {children} 밖 즉, layout.tsx애 적는 것이 맞갰지.
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const resp = await fetch("http://localhost:9999/topics");

  const topics = await resp.json();

  return (
    <html>
      <body>
        <h1>
          <Link href="/">Web</Link>
        </h1>
        <ol>
          {topics.map((item: Topic) => (
            <li key={item.id}>
              <Link href={`/read/${item.id}`}>{item.title}</Link>
            </li>
          ))}
        </ol>
        {children} {/* 여기 있는 children은 page.tsx를 의미 */}
        <TopicButtons />
      </body>
    </html>
  );
}
